version: 2

before:
  hooks:
    - make ebpf

builds:
  - main: ./cmd/ltm
    binary: ltm
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: agent-hellboy
    name: ltm

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
