// Code generated by internal/abi/gen from abi.yaml; DO NOT EDIT.
// sha256: b557d02e6ddad2ca4482faf25eff308bc841bd7cc32f5f59309fd1ee7d725d87

package storage

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS events (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	ts INTEGER NOT NULL,
	category TEXT NOT NULL DEFAULT '',
	action TEXT NOT NULL DEFAULT '',
	pid INTEGER NOT NULL DEFAULT 0,
	ppid INTEGER NOT NULL DEFAULT 0,
	uid INTEGER NOT NULL DEFAULT 0,
	comm TEXT NOT NULL DEFAULT '',
	exe TEXT NOT NULL DEFAULT '',
	container_id TEXT NOT NULL DEFAULT '',
	cgroup_path TEXT NOT NULL DEFAULT '',
	path TEXT NOT NULL DEFAULT '',
	old_path TEXT NOT NULL DEFAULT '',
	local_addr TEXT NOT NULL DEFAULT '',
	local_port INTEGER NOT NULL DEFAULT 0,
	remote_addr TEXT NOT NULL DEFAULT '',
	remote_port INTEGER NOT NULL DEFAULT 0,
	remote_host TEXT NOT NULL DEFAULT '',
	target_pid INTEGER NOT NULL DEFAULT 0,
	exit_code INTEGER NOT NULL DEFAULT 0,
	dropped_before INTEGER NOT NULL DEFAULT 0,
	metadata TEXT NOT NULL DEFAULT '{}',
	raw TEXT NOT NULL DEFAULT '{}'
)`,
	`CREATE INDEX IF NOT EXISTS idx_events_ts ON events(ts)`,
	`CREATE INDEX IF NOT EXISTS idx_events_pid_ts ON events(pid, ts)`,
	`CREATE INDEX IF NOT EXISTS idx_events_path ON events(path)`,
	`CREATE INDEX IF NOT EXISTS idx_events_cat_action_ts ON events(category, action, ts)`,
}

const eventColumns = `id, ts, category, action, pid, ppid, uid, comm, exe, container_id, cgroup_path, path, old_path, local_addr, local_port, remote_addr, remote_port, remote_host, target_pid, exit_code, dropped_before, metadata, raw`

const insertColumns = `ts, category, action, pid, ppid, uid, comm, exe, container_id, cgroup_path, path, old_path, local_addr, local_port, remote_addr, remote_port, remote_host, target_pid, exit_code, dropped_before, metadata, raw`

const insertPlaceholders = `?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?`
