// Code generated by internal/abi/gen from abi.yaml; DO NOT EDIT.
// sha256: 95dfa9f84c9cb4e6261ec9e62a2f6a1df51b4d7e936216cff4171066459e6633

package storage

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS events (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	ts INTEGER NOT NULL,
	category TEXT NOT NULL DEFAULT '',
	action TEXT NOT NULL DEFAULT '',
	pid INTEGER NOT NULL DEFAULT 0,
	ppid INTEGER NOT NULL DEFAULT 0,
	uid INTEGER NOT NULL DEFAULT 0,
	comm TEXT NOT NULL DEFAULT '',
	exe TEXT NOT NULL DEFAULT '',
	container_id TEXT NOT NULL DEFAULT '',
	cgroup_path TEXT NOT NULL DEFAULT '',
	path TEXT NOT NULL DEFAULT '',
	old_path TEXT NOT NULL DEFAULT '',
	local_addr TEXT NOT NULL DEFAULT '',
	local_port INTEGER NOT NULL DEFAULT 0,
	remote_addr TEXT NOT NULL DEFAULT '',
	remote_port INTEGER NOT NULL DEFAULT 0,
	remote_host TEXT NOT NULL DEFAULT '',
	target_pid INTEGER NOT NULL DEFAULT 0,
	exit_code INTEGER NOT NULL DEFAULT 0,
	dropped_before INTEGER NOT NULL DEFAULT 0,
	metadata TEXT NOT NULL DEFAULT '{}',
	raw TEXT NOT NULL DEFAULT '{}'
)`,
	`CREATE INDEX IF NOT EXISTS idx_events_ts ON events(ts)`,
	`CREATE INDEX IF NOT EXISTS idx_events_pid_ts ON events(pid, ts)`,
	`CREATE INDEX IF NOT EXISTS idx_events_path ON events(path)`,
	`CREATE INDEX IF NOT EXISTS idx_events_cat_action_ts ON events(category, action, ts)`,
	`CREATE TABLE IF NOT EXISTS system_samples (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	ts INTEGER NOT NULL,
	cpu_pct REAL NOT NULL DEFAULT 0,
	load1 REAL NOT NULL DEFAULT 0,
	load5 REAL NOT NULL DEFAULT 0,
	load15 REAL NOT NULL DEFAULT 0,
	procs_running INTEGER NOT NULL DEFAULT 0,
	procs_blocked INTEGER NOT NULL DEFAULT 0,
	mem_total_kb INTEGER NOT NULL DEFAULT 0,
	mem_available_kb INTEGER NOT NULL DEFAULT 0,
	swap_total_kb INTEGER NOT NULL DEFAULT 0,
	swap_free_kb INTEGER NOT NULL DEFAULT 0,
	psi_cpu_some_avg10 REAL NOT NULL DEFAULT 0,
	psi_mem_some_avg10 REAL NOT NULL DEFAULT 0,
	psi_mem_full_avg10 REAL NOT NULL DEFAULT 0,
	psi_io_some_avg10 REAL NOT NULL DEFAULT 0,
	psi_io_full_avg10 REAL NOT NULL DEFAULT 0,
	disk_read_kb INTEGER NOT NULL DEFAULT 0,
	disk_write_kb INTEGER NOT NULL DEFAULT 0,
	net_rx_kb INTEGER NOT NULL DEFAULT 0,
	net_tx_kb INTEGER NOT NULL DEFAULT 0,
	net_rx_errs INTEGER NOT NULL DEFAULT 0,
	net_tx_errs INTEGER NOT NULL DEFAULT 0,
	net_rx_drop INTEGER NOT NULL DEFAULT 0,
	net_tx_drop INTEGER NOT NULL DEFAULT 0
)`,
	`CREATE INDEX IF NOT EXISTS idx_system_samples_ts ON system_samples(ts)`,
	`CREATE TABLE IF NOT EXISTS process_samples (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	ts INTEGER NOT NULL,
	pid INTEGER NOT NULL DEFAULT 0,
	comm TEXT NOT NULL DEFAULT '',
	state TEXT NOT NULL DEFAULT '',
	cpu_pct REAL NOT NULL DEFAULT 0,
	rss_kb INTEGER NOT NULL DEFAULT 0,
	threads INTEGER NOT NULL DEFAULT 0,
	read_bytes INTEGER NOT NULL DEFAULT 0,
	write_bytes INTEGER NOT NULL DEFAULT 0,
	cgroup TEXT NOT NULL DEFAULT ''
)`,
	`CREATE INDEX IF NOT EXISTS idx_process_samples_ts ON process_samples(ts)`,
	`CREATE INDEX IF NOT EXISTS idx_process_samples_pid_ts ON process_samples(pid, ts)`,
}

const eventColumns = `id, ts, category, action, pid, ppid, uid, comm, exe, container_id, cgroup_path, path, old_path, local_addr, local_port, remote_addr, remote_port, remote_host, target_pid, exit_code, dropped_before, metadata, raw`

const insertColumns = `ts, category, action, pid, ppid, uid, comm, exe, container_id, cgroup_path, path, old_path, local_addr, local_port, remote_addr, remote_port, remote_host, target_pid, exit_code, dropped_before, metadata, raw`

const insertPlaceholders = `?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?`

const systemSamplesColumns = `id, ts, cpu_pct, load1, load5, load15, procs_running, procs_blocked, mem_total_kb, mem_available_kb, swap_total_kb, swap_free_kb, psi_cpu_some_avg10, psi_mem_some_avg10, psi_mem_full_avg10, psi_io_some_avg10, psi_io_full_avg10, disk_read_kb, disk_write_kb, net_rx_kb, net_tx_kb, net_rx_errs, net_tx_errs, net_rx_drop, net_tx_drop`

const systemSamplesInsertColumns = `ts, cpu_pct, load1, load5, load15, procs_running, procs_blocked, mem_total_kb, mem_available_kb, swap_total_kb, swap_free_kb, psi_cpu_some_avg10, psi_mem_some_avg10, psi_mem_full_avg10, psi_io_some_avg10, psi_io_full_avg10, disk_read_kb, disk_write_kb, net_rx_kb, net_tx_kb, net_rx_errs, net_tx_errs, net_rx_drop, net_tx_drop`

const systemSamplesInsertPlaceholders = `?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?`

const processSamplesColumns = `id, ts, pid, comm, state, cpu_pct, rss_kb, threads, read_bytes, write_bytes, cgroup`

const processSamplesInsertColumns = `ts, pid, comm, state, cpu_pct, rss_kb, threads, read_bytes, write_bytes, cgroup`

const processSamplesInsertPlaceholders = `?, ?, ?, ?, ?, ?, ?, ?, ?, ?`
