//go:build linux

package ebpf

import (
	"context"
	"errors"
	"fmt"
	"os"

	ciliumebpf "github.com/cilium/ebpf"
	"github.com/cilium/ebpf/perf"
	"github.com/cilium/ebpf/rlimit"

	"ltm/internal/storage"
)

type collector struct{}

func NewSource() EventSource { return collector{} }

// The kernel event layout is no longer mirrored by hand: it originates in
// abi.yaml (-> kernel_event.gen.h), and collectorEvent is generated by bpf2go
// from the compiled object's BTF (see gen.go), so the Go struct is derived from
// the same layout the kernel writes and cannot drift from the source of truth.

func (c collector) Run(ctx context.Context, out chan<- storage.Event) error {
	if err := rlimit.RemoveMemlock(); err != nil {
		return err
	}

	bootTime, err := wallClockBootTime()
	if err != nil {
		return err
	}

	spec, err := loadCollector()
	if err != nil {
		return fmt.Errorf("load embedded ebpf object: %w", err)
	}

	coll, err := ciliumebpf.NewCollection(spec)
	if err != nil {
		return fmt.Errorf("create ebpf collection: %w", err)
	}
	defer coll.Close()

	if err := setSelfPID(coll); err != nil {
		return err
	}

	links, attached, skipped, err := attachTracepoints(coll)
	if err != nil {
		return err
	}
	defer func() {
		for _, l := range links {
			_ = l.Close()
		}
	}()
	if attached == 0 {
		return errors.New("no tracepoints could be attached; recording needs root with CAP_BPF and CAP_PERFMON")
	}
	if skipped > 0 {
		fmt.Fprintf(os.Stderr, "ltm: ebpf collector attached %d tracepoints, skipped %d\n", attached, skipped)
	}

	reader, err := perf.NewReader(coll.Maps["events"], 64*4096)
	if err != nil {
		return fmt.Errorf("create perf reader: %w", err)
	}
	defer reader.Close()

	var dropped uint64
	var decodeErrors uint64

	go func() {
		<-ctx.Done()
		_ = reader.Close()
	}()

	for {
		record, err := reader.Read()
		if err != nil {
			if errors.Is(err, perf.ErrClosed) {
				return nil
			}
			return err
		}
		if record.LostSamples != 0 {
			dropped += record.LostSamples
			continue
		}
		ke, err := decodeKernelEvent(record.RawSample)
		if err != nil {
			decodeErrors++
			fmt.Fprintf(os.Stderr, "ltm: dropped malformed kernel event (%d so far): %v\n", decodeErrors, err)
			continue
		}
		ev := convertKernelEvent(bootTime, ke, dropped)
		dropped = 0
		select {
		case out <- ev:
		case <-ctx.Done():
			return nil
		}
	}
}

func setSelfPID(coll *ciliumebpf.Collection) error {
	pidMap, ok := coll.Maps["self_pid"]
	if !ok {
		return nil
	}
	key := uint32(0)
	pid := uint32(os.Getpid())
	return pidMap.Update(&key, &pid, ciliumebpf.UpdateAny)
}
