// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type collectorEvent struct {
	_          structs.HostLayout
	TsNs       uint64
	Bytes      uint64
	Pid        uint32
	Uid        uint32
	LocalPort  uint16
	RemotePort uint16
	LocalIp4   uint32
	RemoteIp4  uint32
	Comm       [16]int8
	Category   [16]int8
	Action     [16]int8
	Path       [128]int8
	OldPath    [128]int8
	SyscallNr  uint32
	Fd         int32
	Aux        uint32
}

type collectorFdKey struct {
	_   structs.HostLayout
	Pid uint32
	Fd  uint32
}

type collectorPathState struct {
	_    structs.HostLayout
	Path [128]int8
}

type collectorRqKey struct {
	_      structs.HostLayout
	Dev    uint32
	_      [4]byte
	Sector uint64
}

// loadCollector returns the embedded CollectionSpec for collector.
func loadCollector() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CollectorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load collector: %w", err)
	}

	return spec, err
}

// loadCollectorObjects loads collector and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*collectorObjects
//	*collectorPrograms
//	*collectorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCollectorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCollector()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// collectorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type collectorSpecs struct {
	collectorProgramSpecs
	collectorMapSpecs
	collectorVariableSpecs
}

// collectorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type collectorProgramSpecs struct {
	TraceBlockRqComplete       *ebpf.ProgramSpec `ebpf:"trace_block_rq_complete"`
	TraceBlockRqError          *ebpf.ProgramSpec `ebpf:"trace_block_rq_error"`
	TraceBlockRqIssue          *ebpf.ProgramSpec `ebpf:"trace_block_rq_issue"`
	TraceOomMarkVictim         *ebpf.ProgramSpec `ebpf:"trace_oom_mark_victim"`
	TraceSchedProcessExit      *ebpf.ProgramSpec `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork      *ebpf.ProgramSpec `ebpf:"trace_sched_process_fork"`
	TraceSchedProcessHang      *ebpf.ProgramSpec `ebpf:"trace_sched_process_hang"`
	TraceSysEnterAccept        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_accept"`
	TraceSysEnterAccept4       *ebpf.ProgramSpec `ebpf:"trace_sys_enter_accept4"`
	TraceSysEnterAccess        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_access"`
	TraceSysEnterBind          *ebpf.ProgramSpec `ebpf:"trace_sys_enter_bind"`
	TraceSysEnterChmod         *ebpf.ProgramSpec `ebpf:"trace_sys_enter_chmod"`
	TraceSysEnterChown         *ebpf.ProgramSpec `ebpf:"trace_sys_enter_chown"`
	TraceSysEnterClone         *ebpf.ProgramSpec `ebpf:"trace_sys_enter_clone"`
	TraceSysEnterClone3        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_clone3"`
	TraceSysEnterClose         *ebpf.ProgramSpec `ebpf:"trace_sys_enter_close"`
	TraceSysEnterConnect       *ebpf.ProgramSpec `ebpf:"trace_sys_enter_connect"`
	TraceSysEnterCopyFileRange *ebpf.ProgramSpec `ebpf:"trace_sys_enter_copy_file_range"`
	TraceSysEnterDup           *ebpf.ProgramSpec `ebpf:"trace_sys_enter_dup"`
	TraceSysEnterDup2          *ebpf.ProgramSpec `ebpf:"trace_sys_enter_dup2"`
	TraceSysEnterDup3          *ebpf.ProgramSpec `ebpf:"trace_sys_enter_dup3"`
	TraceSysEnterExecve        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_execve"`
	TraceSysEnterExecveat      *ebpf.ProgramSpec `ebpf:"trace_sys_enter_execveat"`
	TraceSysEnterFaccessat     *ebpf.ProgramSpec `ebpf:"trace_sys_enter_faccessat"`
	TraceSysEnterFchmod        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_fchmod"`
	TraceSysEnterFchmodat      *ebpf.ProgramSpec `ebpf:"trace_sys_enter_fchmodat"`
	TraceSysEnterFchown        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_fchown"`
	TraceSysEnterFchownat      *ebpf.ProgramSpec `ebpf:"trace_sys_enter_fchownat"`
	TraceSysEnterFtruncate     *ebpf.ProgramSpec `ebpf:"trace_sys_enter_ftruncate"`
	TraceSysEnterKill          *ebpf.ProgramSpec `ebpf:"trace_sys_enter_kill"`
	TraceSysEnterLinkat        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_linkat"`
	TraceSysEnterListen        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_listen"`
	TraceSysEnterLseek         *ebpf.ProgramSpec `ebpf:"trace_sys_enter_lseek"`
	TraceSysEnterMkdir         *ebpf.ProgramSpec `ebpf:"trace_sys_enter_mkdir"`
	TraceSysEnterMkdirat       *ebpf.ProgramSpec `ebpf:"trace_sys_enter_mkdirat"`
	TraceSysEnterMmap          *ebpf.ProgramSpec `ebpf:"trace_sys_enter_mmap"`
	TraceSysEnterMprotect      *ebpf.ProgramSpec `ebpf:"trace_sys_enter_mprotect"`
	TraceSysEnterMunmap        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_munmap"`
	TraceSysEnterNewfstatat    *ebpf.ProgramSpec `ebpf:"trace_sys_enter_newfstatat"`
	TraceSysEnterOpen          *ebpf.ProgramSpec `ebpf:"trace_sys_enter_open"`
	TraceSysEnterOpenat        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_openat"`
	TraceSysEnterOpenat2       *ebpf.ProgramSpec `ebpf:"trace_sys_enter_openat2"`
	TraceSysEnterPipe2         *ebpf.ProgramSpec `ebpf:"trace_sys_enter_pipe2"`
	TraceSysEnterPread64       *ebpf.ProgramSpec `ebpf:"trace_sys_enter_pread64"`
	TraceSysEnterPwrite64      *ebpf.ProgramSpec `ebpf:"trace_sys_enter_pwrite64"`
	TraceSysEnterRead          *ebpf.ProgramSpec `ebpf:"trace_sys_enter_read"`
	TraceSysEnterReadlinkat    *ebpf.ProgramSpec `ebpf:"trace_sys_enter_readlinkat"`
	TraceSysEnterReadv         *ebpf.ProgramSpec `ebpf:"trace_sys_enter_readv"`
	TraceSysEnterRecvfrom      *ebpf.ProgramSpec `ebpf:"trace_sys_enter_recvfrom"`
	TraceSysEnterRecvmsg       *ebpf.ProgramSpec `ebpf:"trace_sys_enter_recvmsg"`
	TraceSysEnterRenameat2     *ebpf.ProgramSpec `ebpf:"trace_sys_enter_renameat2"`
	TraceSysEnterRmdir         *ebpf.ProgramSpec `ebpf:"trace_sys_enter_rmdir"`
	TraceSysEnterSendfile      *ebpf.ProgramSpec `ebpf:"trace_sys_enter_sendfile"`
	TraceSysEnterSendmsg       *ebpf.ProgramSpec `ebpf:"trace_sys_enter_sendmsg"`
	TraceSysEnterSendto        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_sendto"`
	TraceSysEnterShutdown      *ebpf.ProgramSpec `ebpf:"trace_sys_enter_shutdown"`
	TraceSysEnterSocket        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_socket"`
	TraceSysEnterSplice        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_splice"`
	TraceSysEnterSymlinkat     *ebpf.ProgramSpec `ebpf:"trace_sys_enter_symlinkat"`
	TraceSysEnterTgkill        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_tgkill"`
	TraceSysEnterTruncate      *ebpf.ProgramSpec `ebpf:"trace_sys_enter_truncate"`
	TraceSysEnterUnlinkat      *ebpf.ProgramSpec `ebpf:"trace_sys_enter_unlinkat"`
	TraceSysEnterWrite         *ebpf.ProgramSpec `ebpf:"trace_sys_enter_write"`
	TraceSysEnterWritev        *ebpf.ProgramSpec `ebpf:"trace_sys_enter_writev"`
	TraceSysExitOpen           *ebpf.ProgramSpec `ebpf:"trace_sys_exit_open"`
	TraceSysExitOpenat         *ebpf.ProgramSpec `ebpf:"trace_sys_exit_openat"`
	TraceSysExitOpenat2        *ebpf.ProgramSpec `ebpf:"trace_sys_exit_openat2"`
}

// collectorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type collectorMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	FdPath       *ebpf.MapSpec `ebpf:"fd_path"`
	PathScratch  *ebpf.MapSpec `ebpf:"path_scratch"`
	PendingOpen  *ebpf.MapSpec `ebpf:"pending_open"`
	RingbufDrops *ebpf.MapSpec `ebpf:"ringbuf_drops"`
	RqStart      *ebpf.MapSpec `ebpf:"rq_start"`
	SelfPid      *ebpf.MapSpec `ebpf:"self_pid"`
}

// collectorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type collectorVariableSpecs struct {
	LtmUnusedEvent *ebpf.VariableSpec `ebpf:"_ltm_unused_event"`
}

// collectorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCollectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type collectorObjects struct {
	collectorPrograms
	collectorMaps
	collectorVariables
}

func (o *collectorObjects) Close() error {
	return _CollectorClose(
		&o.collectorPrograms,
		&o.collectorMaps,
	)
}

// collectorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCollectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type collectorMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	FdPath       *ebpf.Map `ebpf:"fd_path"`
	PathScratch  *ebpf.Map `ebpf:"path_scratch"`
	PendingOpen  *ebpf.Map `ebpf:"pending_open"`
	RingbufDrops *ebpf.Map `ebpf:"ringbuf_drops"`
	RqStart      *ebpf.Map `ebpf:"rq_start"`
	SelfPid      *ebpf.Map `ebpf:"self_pid"`
}

func (m *collectorMaps) Close() error {
	return _CollectorClose(
		m.Events,
		m.FdPath,
		m.PathScratch,
		m.PendingOpen,
		m.RingbufDrops,
		m.RqStart,
		m.SelfPid,
	)
}

// collectorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCollectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type collectorVariables struct {
	LtmUnusedEvent *ebpf.Variable `ebpf:"_ltm_unused_event"`
}

// collectorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCollectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type collectorPrograms struct {
	TraceBlockRqComplete       *ebpf.Program `ebpf:"trace_block_rq_complete"`
	TraceBlockRqError          *ebpf.Program `ebpf:"trace_block_rq_error"`
	TraceBlockRqIssue          *ebpf.Program `ebpf:"trace_block_rq_issue"`
	TraceOomMarkVictim         *ebpf.Program `ebpf:"trace_oom_mark_victim"`
	TraceSchedProcessExit      *ebpf.Program `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork      *ebpf.Program `ebpf:"trace_sched_process_fork"`
	TraceSchedProcessHang      *ebpf.Program `ebpf:"trace_sched_process_hang"`
	TraceSysEnterAccept        *ebpf.Program `ebpf:"trace_sys_enter_accept"`
	TraceSysEnterAccept4       *ebpf.Program `ebpf:"trace_sys_enter_accept4"`
	TraceSysEnterAccess        *ebpf.Program `ebpf:"trace_sys_enter_access"`
	TraceSysEnterBind          *ebpf.Program `ebpf:"trace_sys_enter_bind"`
	TraceSysEnterChmod         *ebpf.Program `ebpf:"trace_sys_enter_chmod"`
	TraceSysEnterChown         *ebpf.Program `ebpf:"trace_sys_enter_chown"`
	TraceSysEnterClone         *ebpf.Program `ebpf:"trace_sys_enter_clone"`
	TraceSysEnterClone3        *ebpf.Program `ebpf:"trace_sys_enter_clone3"`
	TraceSysEnterClose         *ebpf.Program `ebpf:"trace_sys_enter_close"`
	TraceSysEnterConnect       *ebpf.Program `ebpf:"trace_sys_enter_connect"`
	TraceSysEnterCopyFileRange *ebpf.Program `ebpf:"trace_sys_enter_copy_file_range"`
	TraceSysEnterDup           *ebpf.Program `ebpf:"trace_sys_enter_dup"`
	TraceSysEnterDup2          *ebpf.Program `ebpf:"trace_sys_enter_dup2"`
	TraceSysEnterDup3          *ebpf.Program `ebpf:"trace_sys_enter_dup3"`
	TraceSysEnterExecve        *ebpf.Program `ebpf:"trace_sys_enter_execve"`
	TraceSysEnterExecveat      *ebpf.Program `ebpf:"trace_sys_enter_execveat"`
	TraceSysEnterFaccessat     *ebpf.Program `ebpf:"trace_sys_enter_faccessat"`
	TraceSysEnterFchmod        *ebpf.Program `ebpf:"trace_sys_enter_fchmod"`
	TraceSysEnterFchmodat      *ebpf.Program `ebpf:"trace_sys_enter_fchmodat"`
	TraceSysEnterFchown        *ebpf.Program `ebpf:"trace_sys_enter_fchown"`
	TraceSysEnterFchownat      *ebpf.Program `ebpf:"trace_sys_enter_fchownat"`
	TraceSysEnterFtruncate     *ebpf.Program `ebpf:"trace_sys_enter_ftruncate"`
	TraceSysEnterKill          *ebpf.Program `ebpf:"trace_sys_enter_kill"`
	TraceSysEnterLinkat        *ebpf.Program `ebpf:"trace_sys_enter_linkat"`
	TraceSysEnterListen        *ebpf.Program `ebpf:"trace_sys_enter_listen"`
	TraceSysEnterLseek         *ebpf.Program `ebpf:"trace_sys_enter_lseek"`
	TraceSysEnterMkdir         *ebpf.Program `ebpf:"trace_sys_enter_mkdir"`
	TraceSysEnterMkdirat       *ebpf.Program `ebpf:"trace_sys_enter_mkdirat"`
	TraceSysEnterMmap          *ebpf.Program `ebpf:"trace_sys_enter_mmap"`
	TraceSysEnterMprotect      *ebpf.Program `ebpf:"trace_sys_enter_mprotect"`
	TraceSysEnterMunmap        *ebpf.Program `ebpf:"trace_sys_enter_munmap"`
	TraceSysEnterNewfstatat    *ebpf.Program `ebpf:"trace_sys_enter_newfstatat"`
	TraceSysEnterOpen          *ebpf.Program `ebpf:"trace_sys_enter_open"`
	TraceSysEnterOpenat        *ebpf.Program `ebpf:"trace_sys_enter_openat"`
	TraceSysEnterOpenat2       *ebpf.Program `ebpf:"trace_sys_enter_openat2"`
	TraceSysEnterPipe2         *ebpf.Program `ebpf:"trace_sys_enter_pipe2"`
	TraceSysEnterPread64       *ebpf.Program `ebpf:"trace_sys_enter_pread64"`
	TraceSysEnterPwrite64      *ebpf.Program `ebpf:"trace_sys_enter_pwrite64"`
	TraceSysEnterRead          *ebpf.Program `ebpf:"trace_sys_enter_read"`
	TraceSysEnterReadlinkat    *ebpf.Program `ebpf:"trace_sys_enter_readlinkat"`
	TraceSysEnterReadv         *ebpf.Program `ebpf:"trace_sys_enter_readv"`
	TraceSysEnterRecvfrom      *ebpf.Program `ebpf:"trace_sys_enter_recvfrom"`
	TraceSysEnterRecvmsg       *ebpf.Program `ebpf:"trace_sys_enter_recvmsg"`
	TraceSysEnterRenameat2     *ebpf.Program `ebpf:"trace_sys_enter_renameat2"`
	TraceSysEnterRmdir         *ebpf.Program `ebpf:"trace_sys_enter_rmdir"`
	TraceSysEnterSendfile      *ebpf.Program `ebpf:"trace_sys_enter_sendfile"`
	TraceSysEnterSendmsg       *ebpf.Program `ebpf:"trace_sys_enter_sendmsg"`
	TraceSysEnterSendto        *ebpf.Program `ebpf:"trace_sys_enter_sendto"`
	TraceSysEnterShutdown      *ebpf.Program `ebpf:"trace_sys_enter_shutdown"`
	TraceSysEnterSocket        *ebpf.Program `ebpf:"trace_sys_enter_socket"`
	TraceSysEnterSplice        *ebpf.Program `ebpf:"trace_sys_enter_splice"`
	TraceSysEnterSymlinkat     *ebpf.Program `ebpf:"trace_sys_enter_symlinkat"`
	TraceSysEnterTgkill        *ebpf.Program `ebpf:"trace_sys_enter_tgkill"`
	TraceSysEnterTruncate      *ebpf.Program `ebpf:"trace_sys_enter_truncate"`
	TraceSysEnterUnlinkat      *ebpf.Program `ebpf:"trace_sys_enter_unlinkat"`
	TraceSysEnterWrite         *ebpf.Program `ebpf:"trace_sys_enter_write"`
	TraceSysEnterWritev        *ebpf.Program `ebpf:"trace_sys_enter_writev"`
	TraceSysExitOpen           *ebpf.Program `ebpf:"trace_sys_exit_open"`
	TraceSysExitOpenat         *ebpf.Program `ebpf:"trace_sys_exit_openat"`
	TraceSysExitOpenat2        *ebpf.Program `ebpf:"trace_sys_exit_openat2"`
}

func (p *collectorPrograms) Close() error {
	return _CollectorClose(
		p.TraceBlockRqComplete,
		p.TraceBlockRqError,
		p.TraceBlockRqIssue,
		p.TraceOomMarkVictim,
		p.TraceSchedProcessExit,
		p.TraceSchedProcessFork,
		p.TraceSchedProcessHang,
		p.TraceSysEnterAccept,
		p.TraceSysEnterAccept4,
		p.TraceSysEnterAccess,
		p.TraceSysEnterBind,
		p.TraceSysEnterChmod,
		p.TraceSysEnterChown,
		p.TraceSysEnterClone,
		p.TraceSysEnterClone3,
		p.TraceSysEnterClose,
		p.TraceSysEnterConnect,
		p.TraceSysEnterCopyFileRange,
		p.TraceSysEnterDup,
		p.TraceSysEnterDup2,
		p.TraceSysEnterDup3,
		p.TraceSysEnterExecve,
		p.TraceSysEnterExecveat,
		p.TraceSysEnterFaccessat,
		p.TraceSysEnterFchmod,
		p.TraceSysEnterFchmodat,
		p.TraceSysEnterFchown,
		p.TraceSysEnterFchownat,
		p.TraceSysEnterFtruncate,
		p.TraceSysEnterKill,
		p.TraceSysEnterLinkat,
		p.TraceSysEnterListen,
		p.TraceSysEnterLseek,
		p.TraceSysEnterMkdir,
		p.TraceSysEnterMkdirat,
		p.TraceSysEnterMmap,
		p.TraceSysEnterMprotect,
		p.TraceSysEnterMunmap,
		p.TraceSysEnterNewfstatat,
		p.TraceSysEnterOpen,
		p.TraceSysEnterOpenat,
		p.TraceSysEnterOpenat2,
		p.TraceSysEnterPipe2,
		p.TraceSysEnterPread64,
		p.TraceSysEnterPwrite64,
		p.TraceSysEnterRead,
		p.TraceSysEnterReadlinkat,
		p.TraceSysEnterReadv,
		p.TraceSysEnterRecvfrom,
		p.TraceSysEnterRecvmsg,
		p.TraceSysEnterRenameat2,
		p.TraceSysEnterRmdir,
		p.TraceSysEnterSendfile,
		p.TraceSysEnterSendmsg,
		p.TraceSysEnterSendto,
		p.TraceSysEnterShutdown,
		p.TraceSysEnterSocket,
		p.TraceSysEnterSplice,
		p.TraceSysEnterSymlinkat,
		p.TraceSysEnterTgkill,
		p.TraceSysEnterTruncate,
		p.TraceSysEnterUnlinkat,
		p.TraceSysEnterWrite,
		p.TraceSysEnterWritev,
		p.TraceSysExitOpen,
		p.TraceSysExitOpenat,
		p.TraceSysExitOpenat2,
	)
}

func _CollectorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed collector_bpfel.o
var _CollectorBytes []byte
