//go:build linux

package ebpf

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"net"
	"os"
	"strconv"
	"strings"
	"time"

	ciliumebpf "github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/perf"
	"github.com/cilium/ebpf/rlimit"

	"ltm/internal/abi"
	"ltm/internal/storage"
)

type RealCollector struct{}

// The kernel event layout is no longer mirrored by hand: it originates in
// abi.yaml (-> kernel_event.gen.h), and collectorEvent is generated by bpf2go
// from the compiled object's BTF (see gen.go), so the Go struct is derived from
// the same layout the kernel writes and cannot drift from the source of truth.

func (r RealCollector) Run(ctx context.Context, out chan<- storage.Event) error {
	if err := rlimit.RemoveMemlock(); err != nil {
		return err
	}

	bootTime, err := wallClockBootTime()
	if err != nil {
		return err
	}

	spec, err := loadCollector()
	if err != nil {
		return fmt.Errorf("load embedded ebpf object: %w", err)
	}

	coll, err := ciliumebpf.NewCollection(spec)
	if err != nil {
		return fmt.Errorf("create ebpf collection: %w", err)
	}
	defer coll.Close()

	if err := setSelfPID(coll); err != nil {
		return err
	}

	links := make([]link.Link, 0, len(abi.CollectorTracepoints))
	defer func() {
		for _, l := range links {
			_ = l.Close()
		}
	}()

	var attached, skipped int
	for _, tp := range abi.CollectorTracepoints {
		prog, ok := coll.Programs[tp.Program]
		if !ok {
			// A missing program means the embedded collector_bpfel.o is out of
			// sync with the tracepoint table — a build error, not an
			// environment one, so surface it loudly.
			if tp.Optional {
				skipped++
				continue
			}
			return fmt.Errorf("missing bpf program %q; rebuild collector_bpfel.o with `make ebpf`", tp.Program)
		}
		l, err := link.Tracepoint(tp.Group, tp.Event, prog, nil)
		if err != nil {
			// A tracepoint may be absent or restricted on a given kernel or in
			// a sandboxed VM. Skip it and keep collecting the rest rather than
			// aborting the whole session.
			fmt.Fprintf(os.Stderr, "ltm: skip tracepoint %s/%s: %v\n", tp.Group, tp.Event, err)
			skipped++
			continue
		}
		links = append(links, l)
		attached++
	}
	if attached == 0 {
		return errors.New("no tracepoints could be attached; recording needs root with CAP_BPF and CAP_PERFMON")
	}
	if skipped > 0 {
		fmt.Fprintf(os.Stderr, "ltm: ebpf collector attached %d tracepoints, skipped %d\n", attached, skipped)
	}

	reader, err := perf.NewReader(coll.Maps["events"], 64*4096)
	if err != nil {
		return fmt.Errorf("create perf reader: %w", err)
	}
	defer reader.Close()

	var dropped uint64

	go func() {
		<-ctx.Done()
		_ = reader.Close()
	}()

	for {
		record, err := reader.Read()
		if err != nil {
			if errors.Is(err, perf.ErrClosed) {
				return nil
			}
			return err
		}
		if record.LostSamples != 0 {
			dropped += record.LostSamples
			continue
		}
		var ke collectorEvent
		if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &ke); err != nil {
			continue
		}
		ev := convertKernelEvent(bootTime, ke, dropped)
		dropped = 0
		select {
		case out <- ev:
		case <-ctx.Done():
			return nil
		}
	}
}

func setSelfPID(coll *ciliumebpf.Collection) error {
	pidMap, ok := coll.Maps["self_pid"]
	if !ok {
		return nil
	}
	key := uint32(0)
	pid := uint32(os.Getpid())
	return pidMap.Update(&key, &pid, ciliumebpf.UpdateAny)
}

func convertKernelEvent(bootTime time.Time, ke collectorEvent, dropped uint64) storage.Event {
	ev := storage.Event{
		SchemaVersion: abi.SchemaVersion,
		Timestamp:     bootTime.Add(time.Duration(ke.TsNs)),
		Category:      cstring(ke.Category[:]),
		Action:        cstring(ke.Action[:]),
		PID:           int(ke.Pid),
		UID:           int(ke.Uid),
		Comm:          cstring(ke.Comm[:]),
		Path:          cstring(ke.Path[:]),
		OldPath:       cstring(ke.OldPath[:]),
		LocalPort:     int(ke.LocalPort),
		RemotePort:    int(ke.RemotePort),
		Metadata: map[string]any{
			"syscall_nr": ke.SyscallNr,
			"fd":         ke.Fd,
			"aux":        ke.Aux,
		},
		DroppedBefore: int64(dropped),
	}
	if ke.LocalIp4 != 0 {
		ev.LocalAddr = ipv4String(ke.LocalIp4)
	}
	if ke.RemoteIp4 != 0 {
		ev.RemoteAddr = ipv4String(ke.RemoteIp4)
	}
	if ev.Category == "process" && ev.Action == "exec" && ev.Path != "" {
		ev.Exe = ev.Path
	}
	if ev.Category == "block" {
		// Block events reuse the generic fields to carry disk-request data:
		// ke.Path is the rwbs flag string, ke.Aux the device, ke.SyscallNr the
		// sector count. Replace the misleading generic metadata accordingly.
		ev.Path = ""
		ev.Metadata = map[string]any{
			"dev":       ke.Aux,
			"nr_sector": ke.SyscallNr,
			"rwbs":      cstring(ke.Path[:]),
		}
	}
	if ev.Category == "process" && ev.Action == "fork" && ke.Aux != 0 {
		ev.PPID = int(ke.Aux)
	}
	if ev.Category == "process" && ev.Action == "kill" && ke.Fd > 0 {
		ev.TargetPID = int(ke.Fd)
	}
	if ev.PID > 0 && ev.PPID == 0 && ev.Action != "fork" {
		if ppid, ok := readPPID(ev.PID); ok {
			ev.PPID = ppid
		}
	}
	if ev.Action == "listen" && ev.LocalAddr == "" && ke.Fd >= 0 {
		ev.Metadata["listen_fd"] = ke.Fd
	}
	return ev
}

func wallClockBootTime() (time.Time, error) {
	data, err := os.ReadFile("/proc/stat")
	if err != nil {
		return time.Time{}, err
	}
	for line := range strings.SplitSeq(string(data), "\n") {
		if rest, ok := strings.CutPrefix(line, "btime "); ok {
			sec, err := strconv.ParseInt(strings.TrimSpace(rest), 10, 64)
			if err != nil {
				return time.Time{}, err
			}
			return time.Unix(sec, 0), nil
		}
	}
	return time.Time{}, errors.New("btime not found in /proc/stat")
}

// cstring decodes a NUL-terminated C char array. bpf2go emits char[] fields as
// []int8, so this takes []int8 rather than []byte.
func cstring(b []int8) string {
	n := 0
	for n < len(b) && b[n] != 0 {
		n++
	}
	out := make([]byte, n)
	for i := 0; i < n; i++ {
		out[i] = byte(b[i])
	}
	return string(out)
}

// ipv4String renders an IPv4 address held in a uint32 that was read from the
// kernel's network-byte-order sin_addr via a little-endian struct decode. The
// bytes are therefore already in [a,b,c,d] order little-endian, so encode them
// back out little-endian to recover the original dotted quad.
func ipv4String(v uint32) string {
	var b [4]byte
	binary.LittleEndian.PutUint32(b[:], v)
	return net.IPv4(b[0], b[1], b[2], b[3]).String()
}

func readPPID(pid int) (int, bool) {
	data, err := os.ReadFile(fmt.Sprintf("/proc/%d/stat", pid))
	if err != nil {
		return 0, false
	}
	// Layout: "pid (comm) state ppid ...". comm can contain spaces and
	// parentheses, so parse the fixed fields after the LAST ')'.
	s := string(data)
	rparen := strings.LastIndexByte(s, ')')
	if rparen < 0 || rparen+1 >= len(s) {
		return 0, false
	}
	fields := strings.Fields(s[rparen+1:])
	// fields[0]=state, fields[1]=ppid
	if len(fields) < 2 {
		return 0, false
	}
	ppid, err := strconv.Atoi(fields[1])
	if err != nil {
		return 0, false
	}
	return ppid, true
}
