package abi

// abi.yaml is the single source of truth for the whole ABI: the tracepoint
// table, the persisted event schema, and the kernel->userspace wire layout. The
// generator below compiles it into Go (*_gen.go) and C (kernel_event.gen.h).
// Run `go generate ./internal/abi/` after editing abi.yaml; never hand-edit the
// outputs. (The eBPF object and its Go bindings are then generated by bpf2go
// from the header — see internal/ebpf/gen.go and `make ebpf`.)

//go:generate go run ./gen
