/* Code generated by internal/abi/gen from abi.yaml; DO NOT EDIT. */
// sha256: e7a8c73107d68c64f93afb79ae6f0368c9e9a64ecd1d2ed1f028d46e40bdc098

#pragma once

/*
 * Kernel->userspace transport ABI for ltm capture events. Field order is the
 * on-wire byte order. The integer types (__u64 etc.) are provided by the
 * includer (headers/common.h) before this header.
 */

#define LTM_PATH_MAX_LEN 128
#define LTM_COMM_LEN 16
#define LTM_LABEL_LEN 16

struct ltm_kernel_event {
	__u64 ts_ns;
	__u64 bytes;
	__u32 pid;
	__u32 uid;
	__u16 local_port;
	__u16 remote_port;
	__u32 local_ip4;
	__u32 remote_ip4;
	char comm[LTM_COMM_LEN];
	char category[LTM_LABEL_LEN];
	char action[LTM_LABEL_LEN];
	char path[LTM_PATH_MAX_LEN];
	char old_path[LTM_PATH_MAX_LEN];
	__u32 syscall_nr;
	__s32 fd;
	__u32 aux;
};
