// Code generated by internal/abi/gen from abi.yaml; DO NOT EDIT.
// sha256: e34d1f20131160f37d5dfa51be621092d1c4c1bab7608d7ef3ea6887cd850d9d

package abi

const SchemaVersion = 1

// SchemaDoc describes the queryable data model. It is shown by `ltm query sql`
// with no arguments and embedded in the prompt sent to a configured agent.
const SchemaDoc = `Table: events (one row per collected event)
  id              INTEGER  row id, insertion order
  ts              INTEGER  unix nanoseconds; format with datetime(ts/1e9,'unixepoch')
  category        TEXT     process | file | network | memory | block
  action          TEXT     exec, exit, fork, clone, open, read, write, rename, unlink, bind, connect, listen, ...
  pid             INTEGER  process id
  ppid            INTEGER  parent process id
  uid             INTEGER  user id
  comm            TEXT     process name
  exe             TEXT     resolved executable path
  container_id    TEXT     container id
  cgroup_path     TEXT     cgroup path
  path            TEXT     file path
  old_path        TEXT     rename source path
  local_addr      TEXT     local address
  local_port      INTEGER  local port
  remote_addr     TEXT     remote address
  remote_port     INTEGER  remote port
  remote_host     TEXT     resolved remote hostname
  target_pid      INTEGER  signal/ptrace target pid
  exit_code       INTEGER  process exit code
  dropped_before  INTEGER  events lost immediately before this row
  metadata        TEXT     JSON object; query with json_extract(metadata, '$.key')
  raw             TEXT     JSON object; raw source event

Indexes: ts, (pid, ts), path, (category, action, ts)

Table: system_samples (one row per system-wide resource sample (~1s cadence))
  id                  INTEGER  row id, insertion order
  ts                  INTEGER  unix nanoseconds; format with datetime(ts/1e9,'unixepoch')
  cpu_pct             REAL     CPU busy percent over the interval (0-100)
  load1               REAL     1-minute load average
  load5               REAL     5-minute load average
  load15              REAL     15-minute load average
  procs_running       INTEGER  runnable processes
  procs_blocked       INTEGER  processes blocked on I/O
  mem_total_kb        INTEGER  total RAM (kB)
  mem_available_kb    INTEGER  available RAM (kB)
  swap_total_kb       INTEGER  total swap (kB)
  swap_free_kb        INTEGER  free swap (kB)
  psi_cpu_some_avg10  REAL     CPU pressure some avg10 (percent)
  psi_mem_some_avg10  REAL     memory pressure some avg10 (percent)
  psi_mem_full_avg10  REAL     memory pressure full avg10 (percent)
  psi_io_some_avg10   REAL     I/O pressure some avg10 (percent)
  psi_io_full_avg10   REAL     I/O pressure full avg10 (percent)
  disk_read_kb        INTEGER  disk read over the interval (kB)
  disk_write_kb       INTEGER  disk write over the interval (kB)
  net_rx_kb           INTEGER  network received over the interval (kB)
  net_tx_kb           INTEGER  network transmitted over the interval (kB)
  net_rx_errs         INTEGER  receive errors over the interval
  net_tx_errs         INTEGER  transmit errors over the interval
  net_rx_drop         INTEGER  receive drops over the interval
  net_tx_drop         INTEGER  transmit drops over the interval

Indexes: ts

Table: process_samples (one row per process per sample (~5s cadence))
  id           INTEGER  row id, insertion order
  ts           INTEGER  unix nanoseconds; format with datetime(ts/1e9,'unixepoch')
  pid          INTEGER  process id
  comm         TEXT     process name
  state        TEXT     process state: R S D Z T I
  cpu_pct      REAL     CPU percent over the interval (0-100 per core)
  rss_kb       INTEGER  resident set size (kB)
  threads      INTEGER  thread count
  read_bytes   INTEGER  cumulative bytes read (rchar)
  write_bytes  INTEGER  cumulative bytes written (wchar)
  cgroup       TEXT     cgroup path

Indexes: ts, (pid, ts)`
