// Code generated by internal/abi/gen from abi.yaml; DO NOT EDIT.

package abi

const SchemaVersion = 1

// SchemaDoc describes the queryable data model. It is shown by `ltm query sql`
// with no arguments and embedded in the prompt sent to a configured agent.
const SchemaDoc = `Table: events (one row per collected event)
  id              INTEGER  row id, insertion order
  ts              INTEGER  unix nanoseconds; format with datetime(ts/1e9,'unixepoch')
  category        TEXT     process | file | network | memory | block
  action          TEXT     exec, exit, fork, clone, open, read, write, rename, unlink, bind, connect, listen, ...
  pid             INTEGER  process id
  ppid            INTEGER  parent process id
  uid             INTEGER  user id
  comm            TEXT     process name
  exe             TEXT     resolved executable path
  container_id    TEXT     container id
  cgroup_path     TEXT     cgroup path
  path            TEXT     file path
  old_path        TEXT     rename source path
  local_addr      TEXT     local address
  local_port      INTEGER  local port
  remote_addr     TEXT     remote address
  remote_port     INTEGER  remote port
  remote_host     TEXT     resolved remote hostname
  target_pid      INTEGER  signal/ptrace target pid
  exit_code       INTEGER  process exit code
  dropped_before  INTEGER  events lost immediately before this row
  metadata        TEXT     JSON object; query with json_extract(metadata, '$.key')
  raw             TEXT     JSON object; raw source event

Indexes: ts, (pid, ts), path, (category, action, ts)`
